### ISSUE TITLE
Accessibility of non-interactive toggle triggers

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/css-toggles#10]
We might want to look into what else should happen for an element to 'become activateable' when it's set as a trigger.

**Comment by jerivas** [comment]
MDN has a nice [guide for toggle buttons](https://developer.mozilla.org/en-US/docs/web/accessibility/aria/roles/button_role#toggle_button_example). It looks like we should:

- Add `tabindex`
- Add `role=button`
- Add and update `aria-pressed` according to the state
- Handle clicks as well as Space and Enter keystrokes

I'm unsure how to handle `aria-pressed` on multi-state toggles. Maybe `false` if zero and `true` for all others?

**Comment by mirisuzanne** [comment]
Yeah, it seems they're talking specifically about two and three-way toggles - but it's probably still a good starting point? I think your instinct is right for how to wire up aria-pressed for now. Also looks like we could consider using aria-expanded when visibility is being toggled.
