### ISSUE TITLE
Support proposed @machine rule

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/css-toggles#3]
There has been a lot of interest in the ability to pre-define the allowed 'transitions' from one state to another, all in one place. This is not yet part of the spec, but I [propose a syntax for it](https://css.oddbird.net/toggles/explainer/#triggering-dynamic-transitions) in the explainer -- and I think it would be another good feature to test.

(for now, the `do()` functional syntax might be simplest to support in relation to existing syntax)

**Comment by jerivas** [comment]
An initial implementation was added in 4575f7602a5a8d5245fa2ab6ea5275f39d5df1f4. The codepen demo has been updated accordingly.

Right now the `@machine` definitions break CSS parsing of the other polyfill features, so `@machine` blocks should come at the end of stylesheets (or at least after all other styles related to CSS Toggles).

For anyone trying this out locally, keep in mind you'll need the `toggle-machines.js` script before using `index.js`. I'll start looking into packaging the code correctly so we can continue using a single entry point.

**Comment by jerivas** [comment]
All bugs have been fixed in 808b84791661e8429ebd921c181a235625c300df, and we no longer need the extra file. Just make sure `index.js` is included with `type="module"`.
