### ISSUE TITLE
Support :toggle pseudoclass in css rules

### ISSUE THREAD

**Issue by flackr** [oddbird/css-toggles#6]
Currently the prototype requires selectors like `[data-toggle="switch 1"]` but the eventual syntax will be `:toggle(switch 1)` (see https://css.oddbird.net/toggles/explainer/#selecting-based-on-toggle-state-toggle). I think we could support this in the prototype by rewriting the stylesheets so developers can directly write the real syntax. This is currently done in the container queries polyfill here: https://github.com/GoogleChromeLabs/container-query-polyfill/blob/faf2600f7cd7b16e500f40676dd1b144005bd186/src/cqfill.ts#L37

This should both benefit early experimentation and also mean this could be used as a drop in polyfill eventually.

**Comment by mirisuzanne** [comment]
There was mention elsewhere that the style rewriting in that polyfill was causing issues with some third-party libraries (eg tailwind) because the string-matching was too broad, and rewriting selectors that should have been left alone. I think it could still work, and makes sense to try. But if we go that rout, may be something to keep in mind.

**Comment by jerivas** [comment]
Coincidentally the library we're using as a base for the polyfill already has a [CSS parser](https://github.com/philipwalton/polyfill/blob/master/src/modules/styles-manager.js#L19) that seems pretty robust. I based the [implementation of `@machine` parsing](https://github.com/oddbird/css-toggles/commit/4575f7602a5a8d5245fa2ab6ea5275f39d5df1f4) on that and it might be worth forking it to handle `@machine` as well as rewriting the `:toggle()` pseudoclass.

Would love to get suggestions of other battle tested CSS parsers, preferably with relatively small size and performance footprints.

**Comment by jerivas** [comment]
Transpilation of `:toggle()` has been added in 71959ed31e3721b16ad35f2f96032260ce8b7a58. I ended up going with [css-tree](https://github.com/csstree/csstree) to parse everything and also write back transpiled styles.
