### ISSUE TITLE
Support :toggle(name) without an explicit state

### ISSUE THREAD

**Issue by mirisuzanne** [oddbird/css-toggles#7]
The current demo seems to require a specific state value, eg:

```css
.mode:toggle(light-dark 1) { … }
```

But the spec allows a more flexible selector that should match any non-zero state: 

```css
.mode:toggle(light-dark) { … }
```

I suppose to match that we would need to generate something like:

```css
[data-toggle~="light-dark"]:not([data-toggle~="light-dark 0"]) { … }
```

(There may be an issue here where it's not clear what the 'zero' state is when we're dealing with named states. I'll have to think about that.)

**Comment by jerivas** [comment]
Added in 9156f4e5f4bd6dcdd2127ea1665deadc8e35091b. Currently only checks against a literal `0`, not initial named states

**Comment by jerivas** [comment]
Closing for now, will track named states separately
